[package]
name = "sprachli_bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.3.0"
itertools = "0.10.3"
nom = "7.1.1"
num_enum = "0.5.7"
sprachli_fmt = { path = "../sprachli_fmt" }
sprachli_parser = { path = "../sprachli_parser" }
thiserror = "1.0.31"
